export default {
  /*** GET Products Action Types Declare Here ***/
  GET_PRODUCTS: 'GET_PRODUCTS',
  GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',

  GET_PRODUCT_BY_ID: 'GET_PRODUCT_BY_ID',
  GET_PRODUCT_BY_ID_SUCCESS: 'GET_PRODUCT_BY_ID_SUCCESS',

  /*** GET Categories Action Types Declare Here ***/
  GET_CATEGORIES: 'GET_CATEGORIES',
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',

  GET_CATEGORIES_BY_ID: 'GET_CATEGORIES_BY_ID',
  GET_CATEGORIES_BY_ID_SUCCESS: 'GET_CATEGORIES_BY_ID_SUCCESS',

  /*** POST Products Action Types Declare Here ***/
  POST_PRODUCTS: 'POST_PRODUCTS',
  POST_PRODUCTS_SUCCESS: 'POST_PRODUCTS_SUCCESS',

  /*** Extra Products Action Types Declare Here ***/
  FILTER_PRODUCTS: 'FILTER_PRODUCTS',
};
